#!/bin/bash
#
# Thanks to Calvin Morrison and Sascha Martensen for the base to build
# on top of. The original can be found at
# https://github.com/mutantturkey/mocicon/tree/master/dmenu_mocp
#
# Modifications to inherit parameters from dwm execution along with some
# usability improvements and error handling. Also works normally if
# calling script in some other fashion.
#
# dwm lines for config.def.h
#
# static const char *dmenu_mocp[]  = { "dmenu_mocp", "-m", dmenumon, "-fn", dmenufont, "-nb", col_gray1, "-nf", col_gray3, "-sb", col_cyan, "-sf", col_gray4, NULL };
#
# { MODKEY|ShiftMask,             XK_p,      spawn,          {.v = dmenu_mocp } },

# Edit TERM to your favored terminal
TERM="st -e"

# Edit MUSICDIR to your liking
MUSICDIR=~/music

# Not all of my music has metadata
if [[ ! -z $( mocp -Q %title ) ]]; then
  SONG=$( mocp -Q %title )
else
  SONG=$( mocp -Q %file )
fi

ACTION=$( echo -e "pause/play\nnext\nprevious\nexit\nstart\nopen\nload playlist\nreload playlist\nshuffle\nrepeat\n" | dmenu -p "$SONG" -i "$@" )

if [ "$ACTION" == 'pause/play' ]; then
  mocp -G
fi

if [ "$ACTION" == 'next' ]; then
  mocp -f
fi

if [ "$ACTION" == 'previous' ]; then
  mocp -r
fi

if [ "$ACTION" == 'exit' ]; then
  mocp -x
fi

if [ "$ACTION" == 'start' ]; then
  mocp -S
  dmenu_mocp "$@"
fi

if [ "$ACTION" == 'open' ]; then
  $TERM mocp
fi

if [ "$ACTION" == 'load playlist' ]; then
  mocp -c &&
  playlist=$( find $MUSICDIR -iname "*.m3u" | sort -V | dmenu -p "Load Playlist" -l 10 -i "$@" )
  echo $playlist
  # Infinite loop handling for undefined playlist due to escaping dmenu
  if [[ ! -z "${playlist// }" ]]; then
    mocp -a "$playlist"
    mocp -p
  fi
fi

if [ "$ACTION" == 'reload playlist' ]; then
  mocp -p
fi

if [ "$ACTION" == 'shuffle' ]; then
  mocp -t shuffle
fi

if [ "$ACTION" == 'repeat' ]; then
  mocp -t repeat
fi
